package com.beecode.toolvendor.model;
// Generated Dec 14, 2016 3:53:36 PM by Hibernate Tools 4.3.1


import com.beecode.toolvendor.util.HibernateUtil;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cellar generated by hbm2java
 */
@Entity
@Table(name="cellar"
    , catalog= HibernateUtil.CATALOG
)
public class Cellar  implements java.io.Serializable {


     private Integer id;
     private Integer companyId;
     private String cellar;
     private String address;

    public Cellar() {
    }

	
    public Cellar(Integer company, String cellar, String address) {
       this.companyId = company;
       this.cellar = cellar;
       this.address = address;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@Column(name="company_id", nullable=false)
    public Integer getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    
    @Column(name="cellar", length=45)
    public String getCellar() {
        return this.cellar;
    }
    
    public void setCellar(String cellar) {
        this.cellar = cellar;
    }

    
    @Column(name="address")
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }



}


