package com.beecode.toolvendor.model;
// Generated Dec 14, 2016 3:53:36 PM by Hibernate Tools 4.3.1


import com.beecode.toolvendor.util.HibernateUtil;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name="country"
    , catalog= HibernateUtil.CATALOG
)
public class Country  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String alpha2;
     private String alpha3;
     private Integer number;

    public Country() {
    }

    public Country(String name, String alpha2, String alpha3, Integer number) {
       this.name = name;
       this.alpha2 = alpha2;
       this.alpha3 = alpha3;
       this.number = number;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="alpha2", length=2)
    public String getAlpha2() {
        return this.alpha2;
    }
    
    public void setAlpha2(String alpha2) {
        this.alpha2 = alpha2;
    }

    
    @Column(name="alpha3", length=3)
    public String getAlpha3() {
        return this.alpha3;
    }
    
    public void setAlpha3(String alpha3) {
        this.alpha3 = alpha3;
    }

    
    @Column(name="number")
    public Integer getNumber() {
        return this.number;
    }
    
    public void setNumber(Integer number) {
        this.number = number;
    }


}


