package com.beecode.toolvendor.model;
// Generated Dec 14, 2016 3:53:36 PM by Hibernate Tools 4.3.1


import com.beecode.toolvendor.util.HibernateUtil;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Modules generated by hbm2java
 */
@Entity
@Table(name="modules"
    , catalog= HibernateUtil.CATALOG
)
public class Modules implements java.io.Serializable {


     private int id;
     private String name;
     private String description;
     private String icon;

    public Modules() {
    }

	
    public Modules(int id) {
        this.id = id;
    }
    public Modules(int id, String name, String description, String icon) {
       this.id = id;
       this.name = name;
       this.description = description;
       this.icon = icon;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="icon")
    public String getIcon() {
        return this.icon;
    }
    
    public void setIcon(String icon) {
        this.icon = icon;
    }


}


