package com.beecode.toolvendor.model;
// Generated Dec 14, 2016 3:53:36 PM by Hibernate Tools 4.3.1


import com.beecode.toolvendor.util.HibernateUtil;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductType generated by hbm2java
 */
@Entity
@Table(name="order_type"
    , catalog= HibernateUtil.CATALOG
)
public class OrderType  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Boolean is_sale;

    public OrderType() {
    }

    public OrderType(String name) {
        this.name = name;
        this.is_sale = false;
    }
    
    @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="is_sale")
    public Boolean getSale() {
        return this.is_sale;
    }
    
    public void setSale(Boolean is_sale) {
        this.is_sale = is_sale;
    }


}


