package com.beecode.toolvendor.model;
// Generated Dec 14, 2016 3:53:36 PM by Hibernate Tools 4.3.1


import com.beecode.toolvendor.util.HibernateUtil;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name="order"
    , catalog= HibernateUtil.CATALOG
)
public class Order  implements java.io.Serializable {


     private Integer id;
     private Integer userId;
     private Integer customerId;
     private Integer companyId;
     private Date createdAt;
     private Date lastUpdate;
     private OrderType ordertype;
     private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);

    public Order() {
    }

    public Order(Integer userId, Integer customerId, Integer companyId, Date createdAt, Date lastUpdate, OrderType ordertype, Set<OrderDetail> orderDetails) {
       this.userId = userId;
       this.customerId = customerId;
       this.companyId = companyId;
       this.createdAt = createdAt;
       this.lastUpdate = lastUpdate;
       this.ordertype = ordertype;
       this.orderDetails = orderDetails;
    }
   
@Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name="user_id", nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Column(name="customer_id", nullable=false)
    public Integer getCustomerId() {
        return customerId;
    }

    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
    
    @Column(name="company_id", nullable=false)
    public Integer getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_update", length=19)
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    
@ManyToOne(optional = false)
    @JoinColumn(name="order_type_id", nullable=false)
    public OrderType getOrderType() {
        return this.ordertype;
    }
    
    public void setOrderType(OrderType ordertype) {
        this.ordertype = ordertype;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="order")
    public Set<OrderDetail> getOrderDetails() {
        return this.orderDetails;
    }
    
    public void setOrderDetails(Set<OrderDetail> orderDetails) {
        this.orderDetails = orderDetails;
    }


}


