package com.beecode.toolvendor.model;
// Generated Dec 14, 2016 3:53:36 PM by Hibernate Tools 4.3.1


import com.beecode.toolvendor.util.HibernateUtil;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name="permission"
    , catalog= HibernateUtil.CATALOG
)
public class Permission  implements java.io.Serializable {


     private Integer id;
     private Integer groupId;
     private Integer moduleId;
     private Boolean isread;
     private Boolean iscreate;
     private Boolean isupdate;
     private Boolean isdelete;

    public Permission() {
    }

    public Permission(Integer groupId, Integer moduleId, Boolean isread, Boolean iscreate, Boolean isupdate, Boolean isdelete) {
       this.groupId = groupId;
       this.moduleId = moduleId;
       this.isread = isread;
       this.iscreate = iscreate;
       this.isupdate = isupdate;
       this.isdelete = isdelete;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@Column(name="company_id", nullable=false)
    public Integer getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    @Column(name="module_id", nullable=false)
    public Integer getModuleId() {
        return this.moduleId;
    }
    
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    
    @Column(name="isread")
    public Boolean getIsread() {
        return this.isread;
    }
    
    public void setIsread(Boolean isread) {
        this.isread = isread;
    }

    
    @Column(name="iscreate")
    public Boolean getIscreate() {
        return this.iscreate;
    }
    
    public void setIscreate(Boolean iscreate) {
        this.iscreate = iscreate;
    }

    
    @Column(name="isupdate")
    public Boolean getIsupdate() {
        return this.isupdate;
    }
    
    public void setIsupdate(Boolean isupdate) {
        this.isupdate = isupdate;
    }

    
    @Column(name="isdelete")
    public Boolean getIsdelete() {
        return this.isdelete;
    }
    
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }



}


