package com.beecode.toolvendor.model;
// Generated Dec 14, 2016 3:53:36 PM by Hibernate Tools 4.3.1


import com.beecode.toolvendor.util.HibernateUtil;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Presentation generated by hbm2java
 */
@Entity
@Table(name="presentation"
    , catalog= HibernateUtil.CATALOG
)
public class Presentation  implements java.io.Serializable {


     private Integer id;
     private Integer companyId;
     private String presentation;

    public Presentation() {
    }

	
    public Presentation(Integer companyId, String presentation) {
       this.companyId = companyId;
       this.presentation = presentation;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name="company_id", nullable=false)
    public Integer getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }
    
    @Column(name="presentation", length=45)
    public String getPresentation() {
        return this.presentation;
    }
    
    public void setPresentation(String presentation) {
        this.presentation = presentation;
    }



}


