package com.beecode.toolvendor.model;
// Generated Dec 14, 2016 3:53:36 PM by Hibernate Tools 4.3.1


import com.beecode.toolvendor.util.HibernateUtil;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product"
    , catalog= HibernateUtil.CATALOG
)
public class Product  implements java.io.Serializable {


     private Integer id;
     private Brand brand;
     private Category category;
     private Integer companyId;
     private Family family;
     private Presentation presentation;
     private ProductType productType;
     private String barcode;
     private String name;
     private String description;
     private String detail;
     private Double price;
     private Double tax;
     private Boolean enabled;
     private String photo;
     private Date createdAt;
     private Date lastUpdate;

    public Product() {
    }

	
    public Product(Integer id, Brand brand, Category category, Integer companyId, Family family, Presentation presentation, ProductType productType) {
        this.id = id;
        this.brand = brand;
        this.category = category;
        this.companyId = companyId;
        this.family = family;
        this.presentation = presentation;
        this.productType = productType;
    }
    public Product(Integer id, Brand brand, Category category, Integer companyId, Family family, Presentation presentation, ProductType productType, String barcode, String name, String description, String detail, Double price, Double tax, Boolean enabled, String photo, Date createdAt, Date lastUpdate) {
       this.id = id;
       this.brand = brand;
       this.category = category;
       this.companyId = companyId;
       this.family = family;
       this.presentation = presentation;
       this.productType = productType;
       this.barcode = barcode;
       this.name = name;
       this.description = description;
       this.detail = detail;
       this.price = price;
       this.tax = tax;
       this.enabled = enabled;
       this.photo = photo;
       this.createdAt = createdAt;
       this.lastUpdate = lastUpdate;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(optional = false)
    @JoinColumn(name="brand_id", nullable=false)
    public Brand getBrand() {
        return this.brand;
    }
    
    public void setBrand(Brand brand) {
        this.brand = brand;
    }

@ManyToOne(optional = false)
    @JoinColumn(name="category_id", nullable=false)
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    @Column(name="company_id", nullable=false)
    public Integer getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

@ManyToOne(optional = false)
    @JoinColumn(name="family_id", nullable=false)
    public Family getFamily() {
        return this.family;
    }
    
    public void setFamily(Family family) {
        this.family = family;
    }

@ManyToOne(optional = false)
    @JoinColumn(name="presentation_id", nullable=false)
    public Presentation getPresentation() {
        return this.presentation;
    }
    
    public void setPresentation(Presentation presentation) {
        this.presentation = presentation;
    }

@ManyToOne(optional = false)
    @JoinColumn(name="product_type_id", nullable=false)
    public ProductType getProductType() {
        return this.productType;
    }
    
    public void setProductType(ProductType productType) {
        this.productType = productType;
    }

    
    @Column(name="barcode", length=45)
    public String getBarcode() {
        return this.barcode;
    }
    
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    
    @Column(name="name", length=60)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="detail", length=65535)
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }

    
    @Column(name="price", precision=22, scale=0)
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }

    
    @Column(name="tax", precision=22, scale=0)
    public Double getTax() {
        return this.tax;
    }
    
    public void setTax(Double tax) {
        this.tax = tax;
    }

    
    @Column(name="enabled")
    public Boolean getEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    
    @Column(name="photo")
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_update", length=19)
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }


}


