package com.beecode.toolvendor.model;
// Generated Dec 14, 2016 3:53:36 PM by Hibernate Tools 4.3.1


import com.beecode.toolvendor.util.HibernateUtil;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Promotions generated by hbm2java
 */
@Entity
@Table(name="promotions"
    , catalog= HibernateUtil.CATALOG
)
public class Promotions  implements java.io.Serializable {


     private Integer id;
     private Product product;
     private Date startDate;
     private Date expirationAt;
     private Integer discount;

    public Promotions() {
    }

	
    public Promotions(Product product, Date startDate, Date expirationAt, Integer discount) {
       this.product = product;
       this.startDate = startDate;
       this.expirationAt = expirationAt;
       this.discount = discount;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
@ManyToOne(optional = false)
    @JoinColumn(name="product_id")
    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start_date", length=19)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="expiration_at", length=19)
    public Date getExpirationAt() {
        return this.expirationAt;
    }
    
    public void setExpirationAt(Date expirationAt) {
        this.expirationAt = expirationAt;
    }

    
    @Column(name="discount")
    public Integer getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }




}


