package com.beecode.toolvendor.model;
// Generated Oct 7, 2016 1:11:48 AM by Hibernate Tools 4.3.1


import com.beecode.toolvendor.util.HibernateUtil;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserGroups generated by hbm2java
 */
@Entity
@Table(name="user_groups"
    ,catalog= HibernateUtil.CATALOG
)
public class UserGroups  implements java.io.Serializable {


     private Integer id;
     private Integer groupId;
     private Integer userId;

    public UserGroups() {
    }

    public UserGroups(Integer groupId, Integer userId) {
       this.groupId = groupId;
       this.userId = userId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="group_id", nullable=false)
    public Integer getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    
    @Column(name="user_id", nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }



}


