package com.beecode.toolvendor.model;
// Generated Oct 7, 2016 1:11:48 AM by Hibernate Tools 4.3.1


import com.beecode.toolvendor.util.HibernateUtil;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserZone generated by hbm2java
 */
@Entity
@Table(name="user_zone"
    ,catalog= HibernateUtil.CATALOG
)
public class UserZone  implements java.io.Serializable {


     private Integer id;
     private Integer userId;
     private Integer zoneId;

    public UserZone() {
    }

    public UserZone(Integer userId, Integer zoneId) {
       this.userId = userId;
       this.zoneId = zoneId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="user_id", nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="zone_id", nullable=false)
    public Integer getZoneId() {
        return this.zoneId;
    }
    
    public void setZoneId(Integer zoneId) {
        this.zoneId = zoneId;
    }




}


