package com.beecode.toolvendor.model;
// Generated Dec 14, 2016 3:53:36 PM by Hibernate Tools 4.3.1


import com.beecode.toolvendor.util.HibernateUtil;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VisitPicture generated by hbm2java
 */
@Entity
@Table(name="visit_picture"
    ,catalog= HibernateUtil.CATALOG
)
public class VisitPicture  implements java.io.Serializable {

     private Integer id;
     private Integer visitId;
     private String picture;
     private String comment;

    public VisitPicture() {
    }

    public VisitPicture(Integer visitId, String picture, String comment) {
       this.visitId = visitId;
       this.picture = picture;
       this.comment = comment;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="visit_id", nullable=false)
    public Integer getVisitId() {
        return this.visitId;
    }
    
    public void setVisitId(Integer visitId) {
        this.visitId = visitId;
    }

    @Column(name="picture")
    public String getPicture() {
        return this.picture;
    }
    
    public void setPicture(String picture) {
        this.picture = picture;
    }

    
    @Column(name="comment", length=250)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


